// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwOfkYr8b3SK0Vgwg8_r1FDGwTySOmH5M',
    appId: '1:120618524958:web:f43af1b4733b6618fae90f',
    messagingSenderId: '120618524958',
    projectId: 'ielts-6904a',
    authDomain: 'ielts-6904a.firebaseapp.com',
    storageBucket: 'ielts-6904a.firebasestorage.app',
    measurementId: 'G-7NWM2GS41R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCijqlzz3sM3UO3aoAYDlSBcDcU1_CZLB8',
    appId: '1:120618524958:android:c7dc13d268a22a98fae90f',
    messagingSenderId: '120618524958',
    projectId: 'ielts-6904a',
    storageBucket: 'ielts-6904a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-iZd3Y3G9R4tyioDyRBZnyfVHhbZOdZE',
    appId: '1:120618524958:ios:8eab248ec21b136dfae90f',
    messagingSenderId: '120618524958',
    projectId: 'ielts-6904a',
    storageBucket: 'ielts-6904a.firebasestorage.app',
    iosBundleId: 'com.example.ielts',
  );
}
